// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKu2GPImHMG_xWKb6eVMeek8ceEHAN2oo',
    appId: '1:265358153830:web:13cdaa2de02d070e5475a7',
    messagingSenderId: '265358153830',
    projectId: 'docalendar-35998',
    authDomain: 'docalendar-35998.firebaseapp.com',
    storageBucket: 'docalendar-35998.firebasestorage.app',
    measurementId: 'G-NX2C775265',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9D4XTXOpKvlhamLDwRF51DbWpgsJSUdw',
    appId: '1:265358153830:android:f92465de90fdcaf65475a7',
    messagingSenderId: '265358153830',
    projectId: 'docalendar-35998',
    storageBucket: 'docalendar-35998.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-NDKrmG0gnKw26fsWp_NmpxxJ2aGC3WY',
    appId: '1:265358153830:ios:92fac53e7652fcce5475a7',
    messagingSenderId: '265358153830',
    projectId: 'docalendar-35998',
    storageBucket: 'docalendar-35998.firebasestorage.app',
    iosClientId: '265358153830-oruh3v95tea7cl1og672ofba0e1sgkq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-NDKrmG0gnKw26fsWp_NmpxxJ2aGC3WY',
    appId: '1:265358153830:ios:92fac53e7652fcce5475a7',
    messagingSenderId: '265358153830',
    projectId: 'docalendar-35998',
    storageBucket: 'docalendar-35998.firebasestorage.app',
    iosClientId: '265358153830-oruh3v95tea7cl1og672ofba0e1sgkq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKu2GPImHMG_xWKb6eVMeek8ceEHAN2oo',
    appId: '1:265358153830:web:48a77e5e24f517255475a7',
    messagingSenderId: '265358153830',
    projectId: 'docalendar-35998',
    authDomain: 'docalendar-35998.firebaseapp.com',
    storageBucket: 'docalendar-35998.firebasestorage.app',
    measurementId: 'G-BT76FJKFXC',
  );
}
